[project]
name = "workshop-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-snowflake>=1.10.4",
    "sqlfluff>=3.5.0",
    "sqlfluff-templater-dbt>=3.5.0",
]
